### ISSUE TITLE
ssh target, make kdump_ssh_user/kdump_ssh_server optional?

### ISSUE THREAD

**Issue by jelly** [linux-system-roles/kdump#184]
We have been working on generating an ansible role based on the current kdump configuration in Cockpit and noticed that with an ssh target `kdump_ssh_user` and `kdump_ssh_server`  while they could be found out from the kdump location.

Without it the role fails.
```
localhost | SUCCESS | rc=0 >>
skipped, since /root/.ssh/id_rsa existsDid not run command since '/root/.ssh/id_rsa' exists
localhost | SUCCESS => {
    "changed": false,
    "encoding": "base64",
    "source": "/root/.ssh/id_rsa.pub"
}
localhost | FAILED! => {
    "changed": false,
    "msg": "argument 'name' is of type <class 'NoneType'> and we were unable to convert to str: 'None' is not a string and conversion is not allowed"
}
```

I couldn't find any documentation on `kdump_ssh_user` and `kdump_ssh_server` do the exist to copy the ssh key to the configured kdump user in the kdump location so that you could have a special kdump user to write the dump too?

**Comment by martinpitt** [comment]
Yes please -- currently you have to specify a config like:
```yaml
- name: set up kdump
  hosts: localhost
  vars:
    kdump_target:
      type: ssh
      location: "admin@10.111.113.2"
    kdump_ssh_server: "10.111.113.2"
    kdump_ssh_user: "admin"
  roles:
    - linux-system-roles.kdump
 ```
... and apparently all of the  keys `location`, `kdump_ssh_server`, `kdump_ssh_user` are required. These are redundant and can contradict themselves.
