### ISSUE TITLE
kdump role not writing options to /etc/kdump.conf

### ISSUE THREAD

**Issue by tabowling** [linux-system-roles/kdump#6]
Using example playbook:
```
---
- hosts: rhel7-latest
  become: yes
  become_method: sudo
  become_user: root
  vars:

  roles:
    - role: linux-system-roles.kdump
      core_collector: "makedumpfile -l --message-level 2 -d 31"
      path: /var/mytest/crash
      system_action: reboot  # reboot | halt | poweroff | shell

```

Expected results:

1. Backup file of /etc/kdump.conf should be created in /etc
2. Path should be updated 
3. Core collector should be updated

-vv output
```

PLAYBOOK: example-linux-system-roles.kdump.yml ***********************************************************************************************
1 plays in example-linux-system-roles.kdump.yml

PLAY [rhel7-latest] **************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [rhel7-latest]
META: ran handlers

TASK [linux-system-roles.kdump : Install kexec-tools] ****************************************************************************************
task path: /etc/ansible/roles/linux-system-roles.kdump/tasks/main.yml:2
ok: [rhel7-latest] => {"changed": false, "msg": "", "rc": 0, "results": ["kexec-tools-2.0.7-50.el7.x86_64 providing kexec-tools is already installed"]}

TASK [linux-system-roles.kdump : Find out reserved memory for the crash kernel] **************************************************************
task path: /etc/ansible/roles/linux-system-roles.kdump/tasks/main.yml:7
changed: [rhel7-latest] => {"changed": true, "cmd": ["cat", "/sys/kernel/kexec_crash_size"], "delta": "0:00:00.002173", "end": "2017-05-05 11:07:54.496868", "rc": 0, "start": "2017-05-05 11:07:54.494695", "stderr": "", "stderr_lines": [], "stdout": "0", "stdout_lines": ["0"]}

TASK [linux-system-roles.kdump : Generate /etc/kdump.conf] ***********************************************************************************
task path: /etc/ansible/roles/linux-system-roles.kdump/tasks/main.yml:11
skipping: [rhel7-latest] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [linux-system-roles.kdump : Generate /etc/sysconfig/kdump] ******************************************************************************
task path: /etc/ansible/roles/linux-system-roles.kdump/tasks/main.yml:19
skipping: [rhel7-latest] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************
rhel7-latest               : ok=3    changed=1    unreachable=0    failed=0   

```
